describe('Person page', function () {
  beforeEach(() => {
    cy.server()
    cy.route('GET', '/people', 'fixture:person')
    cy.visit('/#/person')
  })

  it("should have a table with the correct header, data and buttons", function () {
    // Header
    cy.get('thead tr th:nth-child(1)').should('contain', 'ID')
    cy.get('thead tr th:nth-child(2)').should('contain', 'Nombre')

    // Data
    cy.get('tbody').children().should('have.length', 5)
    cy.get('tbody tr:nth-child(1) td:nth-child(1)').should('contain', '4')
    cy.get('tbody tr:nth-child(1) td:nth-child(2)').should('contain', 'Papu')
    cy.get('tbody tr:nth-child(2) td:nth-child(1)').should('contain', '5')
    cy.get('tbody tr:nth-child(2) td:nth-child(2)').should('contain', 'Nono')
    cy.get('tbody tr:nth-child(3) td:nth-child(1)').should('contain', '1')
    cy.get('tbody tr:nth-child(3) td:nth-child(2)').should('contain', 'Leo')
    cy.get('tbody tr:nth-child(4) td:nth-child(1)').should('contain', '3')
    cy.get('tbody tr:nth-child(4) td:nth-child(2)').should('contain', 'Ile')
    cy.get('tbody tr:nth-child(5) td:nth-child(1)').should('contain', '2')
    cy.get('tbody tr:nth-child(5) td:nth-child(2)').should('contain', 'Masi')

    // Buttons
    cy.get('.btn-add').should('contain', 'Agregar').and('not.have.attr', 'disabled')
    cy.get('.btn-edit').should('contain', 'Editar').and('have.attr', 'disabled')
    cy.get('.btn-delete').should('contain', 'Eliminar').and('have.attr', 'disabled')
  })

  it("should add a person successfully", function () {
    const personData = {'id': 6, 'name': 'Mamu'}
    cy.route('POST', '/people', personData)
    cy.get('.btn-add').click()
    cy.get('.edit-modal').should('be.visible')
    cy.get('.edit-modal-title').should('contain', 'Crear persona')
    cy.get("label[for='name']").should('contain', 'Nombre')
    cy.get('.edit-modal-btn-save').should('contain', 'Guardar')
    cy.get('#name').type('Mamu')
    cy.get('.edit-modal-btn-save').click()
    cy.get('tbody').children().should('have.length', 6)
    cy.get('tbody tr:nth-child(1) td:nth-child(1)').should('contain', '4')
    cy.get('tbody tr:nth-child(1) td:nth-child(2)').should('contain', 'Papu')
    cy.get('tbody tr:nth-child(2) td:nth-child(1)').should('contain', '5')
    cy.get('tbody tr:nth-child(2) td:nth-child(2)').should('contain', 'Nono')
    cy.get('tbody tr:nth-child(3) td:nth-child(1)').should('contain', '1')
    cy.get('tbody tr:nth-child(3) td:nth-child(2)').should('contain', 'Leo')
    cy.get('tbody tr:nth-child(4) td:nth-child(1)').should('contain', '3')
    cy.get('tbody tr:nth-child(4) td:nth-child(2)').should('contain', 'Ile')
    cy.get('tbody tr:nth-child(5) td:nth-child(1)').should('contain', '2')
    cy.get('tbody tr:nth-child(5) td:nth-child(2)').should('contain', 'Masi')
    cy.get('tbody tr:nth-child(6) td:nth-child(1)').should('contain', '6')
    cy.get('tbody tr:nth-child(6) td:nth-child(2)').should('contain', 'Mamu')
  })

  it("should delete a person successfully", function () {
    cy.route('DELETE', '/people/1', 1)
    cy.get('tbody tr:nth-child(3)').click()
    cy.get('.btn-delete').click()
    cy.get('.delete-modal').should('be.visible')
    cy.get('.delete-modal-title').should('contain', 'Eliminar persona')
    cy.get('.delete-modal-body p').should('contain', '¿Desea eliminar los elementos seleccionados?')
    cy.get('.delete-modal-btn-delete').should('contain', 'Eliminar')
    cy.get('.delete-modal-btn-cancel').should('contain', 'Cancelar')
    cy.get('.delete-modal-btn-delete').click()
    cy.get('tbody').children().should('have.length', 4)
    cy.get('tbody tr:nth-child(1) td:nth-child(1)').should('contain', '4')
    cy.get('tbody tr:nth-child(1) td:nth-child(2)').should('contain', 'Papu')
    cy.get('tbody tr:nth-child(2) td:nth-child(1)').should('contain', '5')
    cy.get('tbody tr:nth-child(2) td:nth-child(2)').should('contain', 'Nono')
    cy.get('tbody tr:nth-child(3) td:nth-child(1)').should('contain', '3')
    cy.get('tbody tr:nth-child(3) td:nth-child(2)').should('contain', 'Ile')
    cy.get('tbody tr:nth-child(4) td:nth-child(1)').should('contain', '2')
    cy.get('tbody tr:nth-child(4) td:nth-child(2)').should('contain', 'Masi')
  })

  it("should delete more than one person successfully", function () {
    cy.route('DELETE', '/people/1', 1)
    cy.route('DELETE', '/people/2', 2)
    cy.get('tbody tr:nth-child(3)').click()
    cy.get('tbody tr:nth-child(5)').click()
    cy.get('.btn-delete').click()
    cy.get('.delete-modal').should('be.visible')
    cy.get('.delete-modal-title').should('contain', 'Eliminar persona')
    cy.get('.delete-modal-body p').should('contain', '¿Desea eliminar los elementos seleccionados?')
    cy.get('.delete-modal-btn-delete').should('contain', 'Eliminar')
    cy.get('.delete-modal-btn-cancel').should('contain', 'Cancelar')
    cy.get('.delete-modal-btn-delete').click()
    cy.get('tbody').children().should('have.length', 3)
    cy.get('tbody tr:nth-child(1) td:nth-child(1)').should('contain', '4')
    cy.get('tbody tr:nth-child(1) td:nth-child(2)').should('contain', 'Papu')
    cy.get('tbody tr:nth-child(2) td:nth-child(1)').should('contain', '5')
    cy.get('tbody tr:nth-child(2) td:nth-child(2)').should('contain', 'Nono')
    cy.get('tbody tr:nth-child(3) td:nth-child(1)').should('contain', '3')
    cy.get('tbody tr:nth-child(3) td:nth-child(2)').should('contain', 'Ile')
  })
})
